### ISSUE TITLE
这么早开源真的好吗

### ISSUE THREAD

**Issue by ZeroWeight** [mcfloundinho/countdown#1]
## 毕竟还没考试没出成绩，万一真666了怎么办  
![](https://a-ssl.duitang.com/uploads/item/201601/10/20160110211234_NATCz.jpeg)
等出了成绩在发会死人吗
## 我不会再提醒你红姐姐管教务这件事情了
没了

**Comment by yiwenlu66** [comment]
@ZeroWeight 感谢提醒！

然而并没有协议规定 EDA 大作业的源代码不得公开。考虑到现在 EDA 大作业已经验收完毕，公开源代码并不会给试图抄袭者带来便利。即使现在被抄袭，我作为不知情的一方，不可能有主动包庇抄袭的意图，因此不应承担责任。当然我应该加一个 disclaimer 倒是真的。
